spring:
  datasource:
    url: jdbc:h2:~/challenge01
    username: SA
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      
    
  